# Gaussian Mixture Models

## Univariate Gaussian Mixture Models

<!-- Discussion of the model goes here -->


### Implementation

```{r}

ugmm <- function(X, K, tol) {
  
  # Basics of X
  N <- length(X)
  
  # Initialise by randomly assigning to clusters
  c <- sample(1:K, N, replace=T)
  mu <- numeric()
  theta <- numeric()
  prop <- numeric()
  for (k in 1:K) {
    mu <- c(mu, mean(X[c == k]))
    theta <- c(theta, var(X[c == k]))
    prop <- c(prop, length((X[c == k]))/length(X))
  }
  
  # # Initialise means
  # mu <- sample(X, K)
  # 
  # # Initialise variances
  # theta <- runif(K, min=1, max=var(X))#rep(var(X)^(1/K), K)
  # 
  # # Initialise mixing proportions
  # prop <- rep(1/K, K)

  # Initialise individual label probabilities and weighted densities
  g <- matrix(0, nrow=N, ncol=K)
  
  # Initialise the difference
  diff <- Inf
  old <- 0
  
  # Counter
  i <- 0
  
  # EM Algo
  while (TRUE) {
    
    # Update count
    i <- i + 1
    # print(i)
    
    # Old values
    oldmu <- mu
    oldtheta <- theta
    oldprop <- prop
    
    # E-step
    w <- matrix(numeric(N*K), nrow=N, ncol=K)
    for (k in 1:K) {
      g[,k] <- prop[k] * dnorm(X, mu[k], sqrt(theta[k]))
    }
    g <- g / rowSums(g)
    
    
    # M-step
    Nk <- rowSums(g)
    for (k in 1:K) {
      
      # Calculate mu_k
      mu[k] <- (1/Nk[k]) * sum(g[,k] * x)
      
      # Calculate theta^2_k
      theta[k] <- (1/Nk[k])*sum(g[,k]*(x - mu[k])^2)
      
      # Update mixing proportions
      prop[k] <- Nk[k]/N
      
    }
    
    # Calculate log-likelihood
    # lli <- numeric(N)
    # for (k in 1:K) {
    #   lli <- lli + g[,k] * (log(prop[k]) + log(dnorm(X, mu[k], sqrt(theta[k]))))
    # }
    # ll <- sum(lli)
    
    # Recalulate difference
    # diff <- abs(ll - old)
    # print(apply(g, 2, mean))
    print(mu)
    # print(theta)
    # print(paste0("LL: ", ll))
    # print(paste0("diff: ", diff))
    
    # Check
    # if (diff < tol) break
    if (max(abs(rbind(oldmu, oldtheta, oldprop) - rbind(mu, theta, prop))) < tol) break
    
    # Assume the loop hasn't ended, update the old ll
    # old <- ll
    
  }
  
  return(list(mu=mu, theta=sqrt(theta), prop=prop))

}


```

Testing the function:

```{r}

# Simulate draws from 3 distributions
set.seed(1234)
x1 <- rnorm(1000, 0, 1)
x2 <- rnorm(1500, -4, 2)
x3 <- rnorm(500, 2, 0.5)

# Combine into single vector
x <- c(x1, x2, x3)

# Density Plot
plot(density(x))

# Estimate clusters
ugmm(x, 3, 0.0001)

```
