--- 
title: "Collected R Code"
author: "Phil Swatton"
date: ""
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
github-repo: philswatton/Collected-R-Code
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

```{r eval=F, echo=F}

bookdown::render_book("index.Rmd")

```

# Introduction

This is a collection of R code written for the purposes of practice and demonstration. At the moment this is all in a work in progress stage. The long-term goal is to include lots of statistical and machine learning algorithms, covering model estimation and data reduction. I may also include some other interesting algorithms down the line.

Beyond giving me both a venue for solidifying my understanding and acting as a sort of online advert for my skillset, I also hope that this document will end up being of use to some other people.

I'm in no small part inspired by a similar project by Michael Clark, which you can find [at this link](https://m-clark.github.io/models-by-example/). The code here is my own, but the inspiration should be clear. The main difference from Michael's document to mine is I'm placing more emphasis on building more 'complete' functions - i.e. they should be workable beyond the example being provided. There's therefore slightly more of a programming emphasis in this document and it's this niche that this document fills.
